name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Make
        run: sudo apt-get install make

      - name: Setup project
        run: make setup

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint
